nelmio_cors:
  defaults:
    # By default: false
    allow_credentials: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    # By default: []
    allow_headers: ['Content-Type', 'Authorization']
    # By default: []
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    expose_headers: []
    # By default: 0
    max_age: 3600
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  # By default: '^/': ~
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['X-Custom-Auth']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      max_age: 3600
    '^/':
      origin_regex: true
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_headers: ['X-Custom-Auth']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      max_age: 3600
      hosts: ['^api\.']
