security:
  # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username
    in_memory:
      memory:
        users:
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  # activate different ways to authenticate
  # http_basic: ~
  # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
  # form_login: ~
  # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
  firewalls:
    main:
      anonymous: true
      pattern: ^/
      form_login:
        provider:   fos_userbundle
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        #csrf_provider: security.csrf.token_manager
      logout:
        path:   fos_user_security_logout
        target: front_index_page
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

  encoders:
    FOS\UserBundle\Model\UserInterface: sha512 # bcrypt

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/group, roles: ROLE_ADMIN }
    - { path: ^/register, roles: ROLE_ADMIN }
    - { path: ^/resetting, roles: ROLE_ADMIN }
    - { path: ^/change_password, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_ADMIN }
    - { path: .*/admin/, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_STOIC: ROLE_USER, ROLE_ADMIN
