twig:
  paths: ['%kernel.project_dir%/templates']
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    app_env: '%app_env%'
    app_prefix: '%app_prefix%'
    domain: '%domain%'
#  form_themes:
#    - '@RainlikeAdminBundle/Resources/views/components/vich/fields.html.twig'
